### ISSUE TITLE
POST Request to get data results in `404`

### ISSUE THREAD

**Issue by wanze** [zsoltjanes/statamic-ai-writer-for-bard#2]
Hi,

First of all, thank you for creating for this addon! :)

### Description

The current release does not work locally: The `POST` request to `/!/statamic-bard-openai/` results in redirect (`301`) and then a `404` because it tries to serve the page via `GET` instead of `POST`.

<img width="711" alt="Screenshot 2023-03-27 at 10 48 34" src="https://user-images.githubusercontent.com/2118742/227890957-f4eb0502-1be9-4ab6-9b9e-93521e5caf8c.png">

### Solution

Remove the trailing slash for the request: `/!/statamic-bard-openai` here: https://github.com/zsoltjanes/statamic-ai-writer-for-bard/blob/master/resources/js/Menu.vue#L82

**Comment by zsoltjanes** [comment]
Hi @wanze! Thanks for reporting your issue. I deleted the trailing slash, please update your addon and reply back to me if it works.

**Comment by wanze** [comment]
Thanks for the fix and release, it works! 👍
